config/routes.rb
Rails.application.routes.draw do
  root "home#index"

  resources :blog_posts, path: "blog", param: :name
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
  validates :name, presence: true, uniqueness: true

  before_save :assign_permalink

  def to_param
    self.name
  end

  private

  def assign_permalink
    self.url = "/blog/#{self.name.parameterize}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/blog_posts_controller.rb
class BlogPostsController < ApplicationController
  before_action :set_blog_post, only: %i[ show edit update destroy ]

  def index
    @blog_posts = BlogPost.all
  end

  def show
  end

  def new
    @blog_post = BlogPost.new
  end

  def create
    @blog_post = BlogPost.new(blog_post_params)

    if @blog_post.save
      redirect_to blog_post_path(@blog_post.name), notice: "Blog post was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @blog_post.update(blog_post_params)
      redirect_to blog_post_path(@blog_post.name), notice: "Blog post was successfully updated.", status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @blog_post.destroy!
    redirect_to root_path, notice: "Blog post was successfully destroyed.", status: :see_other
  end

  private
    def set_blog_post
      @blog_post = BlogPost.find_by!(name: params.expect(:name))
    end

    def blog_post_params
      params.expect(blog_post: [ :name ])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blog_posts_helper.rb
module BlogPostsHelper
end

app/views/blog_posts/_blog_post.html.erb
<div id="<%= dom_id blog_post %>">
  <p>
    <strong>Name:</strong>
    <%= blog_post.name %>
  </p>

  <p>
    <strong>Url:</strong>
    <%= blog_post.url %>
  </p>

</div>

app/views/blog_posts/_blogs.html.erb
<%# locals: (header:, posts:) %>

<h1><%= header %></h1>

<% posts.each do |post| %>
  <%= post %>
<% end %>

app/views/blog_posts/_form.html.erb
<%= form_with(model: blog_post, url: blog_post.url) do |form| %>
  <% if blog_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(blog_post.errors.count, "error") %> prohibited this blog_post from being saved:</h2>

      <ul>
        <% blog_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/blog_posts/edit.html.erb
<% content_for :title, "Editing blog post" %>

<h1>Editing blog post</h1>

<%= render "form", blog_post: @blog_post %>

<br>

<div>
  <%= link_to "Show this blog post", @blog_post.url %> |
  <%= link_to "Back to blog posts", root_path %>
</div>

app/views/blog_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Blog posts" %>

<div id="blog_posts" class="blog-posts">
  <%= render BlogComponent.new do |component| %>
    <% component.with_header do %>
      <%= link_to "My blog", root_path %>
    <% end %>

    <% BlogPost.all.each do |blog_post| %>
      <% component.with_post do %>
        <%= link_to blog_post.name, blog_post.url %>
      <% end %>
    <% end %>
  <% end %>

  <%= link_to "New blog post", new_blog_post_path, class: 'btn btn-primary' %>
</div>

app/views/blog_posts/new.html.erb
<% content_for :title, "New blog post" %>

<h1>New blog post</h1>

<%= render "form", blog_post: @blog_post %>

<br>

<div>
  <%= link_to "Back to blog posts", root_path %>
</div>

app/views/blog_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @blog_post %>

<div>
  <%= link_to "Edit this blog post", edit_blog_post_path(@blog_post.name) %> |
  <%= link_to "Back to blog posts", root_path %>

  <%= button_to "Destroy this blog post", blog_post_path(@blog_post.name), method: :delete %>
</div>

app/views/home/index.html.erb
<h1>RootPage</h1>
<p><%= link_to "To blog list", blog_posts_path %></p>

<div id="blog_posts" class="blog-posts">
  <%= render BlogComponent.new do |component| %>
    <% BlogPost.all.each do |blog_post| %>
      <% component.with_post do %>
        <div>
          <span><%= blog_post.name %></span>
          <span class="small text-muted"><%= blog_post.updated_at.strftime("%Y年%m月%d日") %></span>
        </div>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "View Component App" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>